spring:
  application:
    name: time-flow-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/timeflow}
    username: ${DB_USERNAME:timeflow}
    password: ${DB_PASSWORD:timeflow}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${PORT:8080}
